GET http://localhost:4545/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbmVAZG9lLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTU5MjgzMDQ2MywiZXhwIjoxNTkyODM0MDYzfQ.3EAW6dUXMeUAO6MGUh96adjBqVc_6ybzjsYg8zwDYs0

###

POST http://localhost:4545/users HTTP/1.1
Content-Type: application/json

{
  "firstName": "Nicolas"
}

###

PUT http://localhost:4545/users/159bdf1b-e1f0-4b4b-b567-1a0ccb064cf4 HTTP/1.1
Content-Type: application/json

{
  "firstName" : "Jane",
  "lastName": "Dock"
}

###

POST http://localhost:4545/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "jane@doe.com",
  "password": "toto"
}

